### ISSUE TITLE
Ability to build as dynamic Nginx module

### ISSUE THREAD

**Issue by dvershinin** [limithit/NginxExecute#1]
Can you update module config so it can be built as dynamic module.

**Comment by limithit** [comment]
When the space, the latter will add this feature, thank you for your feedback

**Comment by limithit** [comment]
Later will add this function, thank you for your feedback

**Comment by dvershinin** [comment]
Please see my PR. For compiling dynamic module I have verified it to work fine.

**Comment by dvershinin** [comment]
Thanks. Can you make another release (1.6?) so I can package the dynamic module as RPM? 
I have collection of built dynamic modules for stable Nginx 1.12.0 here: https://extras.getpagespeed.com/redhat/7/x86_64/RPMS/

**Comment by limithit** [comment]
As you wish, a new version has been rebuilt. You can pack RPM finally thank you for your perfect.

**Comment by dvershinin** [comment]
Hi @limithit,

I have compiled the module and packaged it for Nginx 1.12.0 on CentOS (will submit PR for the Readme later on). Noticed a few issues now that I finally got my hands into testing the module itself. Will submit another ticket.
